release                                       = "23.1"
venue                                         = "test"
eks_cluster_name                              = "<INSERT-EKS-CLUSTER-NAME>"
kubeconfig_filepath                           = "<INSERT-EKS-CLUSTER-KUBECONFIG-PATH>"
uads_development_efs_fsmt_id                  = "fsmt-06c1de455bed6a67b"
default_group_node_group_name                 = "defaultgroupNodeGroup"
default_group_node_group_launch_template_name = "<INSERT-EKS-DEFAULT-NODE-GROUP-LAUNCH-TEMPLATE-NAME>"
elb_subnet                                    = "subnet-0ca61daf80bc568d9"
