release                                       = "23.1"
venue                                         = "test"
eks_cluster_name                              = "<INSERT-EKS-CLUSTER-NAME>"
kubeconfig_filepath                           = "<INSERT-EKS-CLUSTER-KUBECONFIG-PATH>"
uads_development_efs_fsmt_id                  = "fsmt-06c1de455bed6a67b"
default_group_node_group_name                 = "defaultgroupNodeGroup"
default_group_node_group_launch_template_name = "<INSERT-EKS-DEFAULT-NODE-GROUP-LAUNCH-TEMPLATE-NAME>"
elb_subnet                                    = "subnet-0ca61daf80bc568d9"

docker_images = {
  hysds_core         = "ghcr.io/unity-sds/unity-sps-prototype/hysds-core:unity-v1.0.0"
  hysds_ui           = "ghcr.io/unity-sds/unity-sps-prototype/hysds-ui-remote:unity-v1.0.0"
  hysds_mozart       = "ghcr.io/unity-sds/unity-sps-prototype/hysds-mozart:unity-v1.0.0"
  hysds_grq2         = "ghcr.io/unity-sds/unity-sps-prototype/hysds-grq2:unity-v1.0.0"
  hysds_verdi        = "ghcr.io/unity-sds/unity-sps-prototype/hysds-verdi:unity-v1.0.0"
  hysds_factotum     = "ghcr.io/unity-sds/unity-sps-prototype/hysds-factotum:unity-v1.0.0"
  ades_wpst_api      = "ghcr.io/unity-sds/unity-sps-prototype/ades-wpst-api-mcp-test-tmp:unity-v1.0.0"
  sps_api            = "ghcr.io/unity-sds/unity-sps-prototype/sps-api:unity-v1.0.0"
  sps_hysds_pge_base = "ghcr.io/unity-sds/unity-sps-prototype/sps-hysds-pge-base:unity-v1.0.0"
  logstash           = "docker.elastic.co/logstash/logstash:7.10.2"
  rabbitmq           = "rabbitmq:3.11.13-management"
  busybox            = "busybox:1.36.0"
  redis              = "redis:7.0.10"
  dind               = "docker:23.0.3-dind"
}
