release                                       = "23.1"
venue                                         = "dev"
eks_cluster_name                              = "<INSERT-EKS-CLUSTER-NAME>"
kubeconfig_filepath                           = "<INSERT-EKS-CLUSTER-KUBECONFIG-PATH>"
uads_development_efs_fsmt_id                  = "fsmt-06d161d46a1b16cb6"
default_group_node_group_name                 = "dafaultgroupNodeGroup"
default_group_node_group_launch_template_name = "<INSERT-EKS-DEFAULT-NODE-GROUP-LAUNCH-TEMPLATE-NAME>"
elb_subnet                                    = "subnet-087b54673c7549e2d"
