release                                       = "23.1"
venue                                         = "dev"
eks_cluster_name                              = "<INSERT-EKS-CLUSTER-NAME>"
kubeconfig_filepath                           = "<INSERT-EKS-CLUSTER-KUBECONFIG-PATH>"
uads_development_efs_fsmt_id                  = "fsmt-06d161d46a1b16cb6"
default_group_node_group_name                 = "dafaultgroupNodeGroup"
default_group_node_group_launch_template_name = "<INSERT-EKS-DEFAULT-NODE-GROUP-LAUNCH-TEMPLATE-NAME>"
elb_subnet                                    = "subnet-087b54673c7549e2d"

docker_images = {
  hysds_core         = "ghcr.io/unity-sds/unity-sps-prototype/hysds-core:1.0.0"
  hysds_ui           = "ghcr.io/unity-sds/unity-sps-prototype/hysds-ui-remote:1.0.0"
  hysds_mozart       = "ghcr.io/unity-sds/unity-sps-prototype/hysds-mozart:1.0.0"
  hysds_grq2         = "ghcr.io/unity-sds/unity-sps-prototype/hysds-grq2:1.0.0"
  hysds_verdi        = "ghcr.io/unity-sds/unity-sps-prototype/hysds-verdi:1.0.0"
  hysds_factotum     = "ghcr.io/unity-sds/unity-sps-prototype/hysds-factotum:1.0.0"
  ades_wpst_api      = "ghcr.io/unity-sds/unity-sps-prototype/ades-wpst-api-mcp-dev-tmp:1.0.0"
  sps_api            = "ghcr.io/unity-sds/unity-sps-prototype/sps-api-fork:1.0.0"
  sps_hysds_pge_base = "ghcr.io/unity-sds/unity-sps-prototype/sps-hysds-pge-base:1.0.0"
  logstash           = "docker.elastic.co/logstash/logstash:7.10.2"
  rabbitmq           = "rabbitmq:3-management"
  busybox            = "k8s.gcr.io/busybox"
  redis              = "redis:latest"
  dind               = "docker:dind"
}
