---
clusterName: "grq-es"

# Permit co-located instances for solitary minikube virtual machines.
antiAffinity: "soft"

# Shrink default JVM heap.
esJavaOpts: "-Xmx512m -Xms512m"

# Allocate smaller chunks of memory per pod.
resources:
  requests:
    cpu: "1000m"
    memory: "2Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

# Request smaller persistent volumes.
volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  storageClassName: "hostpath"
  resources:
    requests:
      storage: 5Gi

# elasticsearch:
masterService: "grq-es"

# because we're using 1 node the cluster health will be YELLOW instead of GREEN after data is ingested
clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"

replicas: 1

service:
  type: "LoadBalancer"

httpPort: 9201
transportPort: 9301

esConfig:
  elasticsearch.yml: |
    http.cors.enabled : true
    http.cors.allow-origin: "*"
    http.port: 9201
