apiVersion: v1
kind: Pod
metadata:
  name: orchestrator
spec:
  containers:
    - name: orchestrator
      image: hysds-core:unity-v0.0.1
      command: ["supervisord", "--nodaemon"]
      volumeMounts:
        - name: celeryconfig
          mountPath: /home/ops/hysds/celeryconfig.py
          subPath: celeryconfig.py
        - name: supervisord-orchestrator
          mountPath: /home/ops/supervisord.conf
          subPath: supervisord.conf
  volumes:
    - name: celeryconfig
      configMap:
        name: celeryconfig
    - name: supervisord-orchestrator
      configMap:
        name: supervisord-orchestrator
