apiVersion: v1
kind: Pod
metadata:
  name: orchestrator
spec:
  containers:
    - name: orchestrator
      image: hysds-core:unity-v0.0.1
      command: ["supervisord", "--nodaemon"]
      # resources:
      #   requests:
      #     cpu: 500m
      #     memory: 1Gi
      volumeMounts:
        - name: celeryconfig
          mountPath: /root/hysds/celeryconfig.py
          subPath: celeryconfig.py
        - name: supervisord-orchestrator
          mountPath: /root/supervisord.conf
          subPath: supervisord.conf
  volumes:
    - name: celeryconfig
      configMap:
        name: celeryconfig
    - name: supervisord-orchestrator
      configMap:
        name: supervisord-orchestrator
