apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  type: LoadBalancer
  ports:
    - name: minio-api
      port: 9000
      targetPort: 9000
      protocol: TCP
    - name: minio-interface
      port: 9001
      protocol: TCP
  selector:
    app: minio

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - image: "minio/minio:latest"
          name: minio
          args:
            - server
            - /storage
            - --console-address=:9001
          env:
            - name: MINIO_ACCESS_KEY
              value: hysds
            - name: MINIO_SECRET_KEY
              value: password
          ports:
            - containerPort: 9000
              hostPort: 9000
            - containerPort: 9001
              hostPort: 9001
          volumeMounts:
            - name: storage # must match the volume name
              mountPath: "/storage"
      volumes:
        - name: storage
          persistentVolumeClaim:
            # Name of the PVC created earlier
            claimName: minio-pv-claim
