# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: minio-pv
#   labels:
#     type: local
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 20Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/private/tmp/buckets"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pv-claim
  labels:
    app: minio-storage-claim
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName: manual
  resources:
    requests:
      storage: 20Gi
