FROM oraclelinux:8

ARG HOME=/root
ARG VERSION="3.9.5"

WORKDIR $HOME

# RUN yum update -y && \
RUN yum install gcc tar openssl-devel bzip2-devel libffi-devel openldap-devel readline-devel make wget git -y && \
  cd /tmp && \
  # installing python 3
  wget https://www.python.org/ftp/python/${VERSION}/Python-${VERSION}.tgz && \
  tar xzf Python-${VERSION}.tgz && \
  cd Python-${VERSION} && \
  ./configure --enable-optimizations && \
  make altinstall && \
  ln -s /usr/local/bin/python${VERSION:0:3} /usr/local/bin/python3 && \
  ln -s /usr/local/bin/pip${VERSION:0:3} /usr/local/bin/pip3 && \
  pip3 install --no-cache-dir --upgrade pip && \
  pip3 install --no-cache-dir gnureadline && \
  rm -f /tmp/Python-${VERSION}.tgz && \
  rm -rf /tmp/Python-${VERSION}

# installing HySDS libraries
RUN cd $HOME && \
  git clone https://github.com/hysds/prov_es.git && \
  git clone https://github.com/hysds/osaka.git && \
  git clone https://github.com/hysds/hysds_commons.git && \
  git clone https://github.com/hysds/hysds.git && \
  pip3 install --no-cache-dir -e prov_es/ && \
  pip3 install --no-cache-dir -e osaka/ && \
  pip3 install --no-cache-dir -e hysds_commons/ && \
  pip3 install --no-cache-dir -e hysds/ && \
  yum clean all && \
  rm -rf /var/cache/yum && \
  rm -r /tmp/*

# # osaka/  # installs Werkzeug 2.0.1
# # https://github.com/hysds/osaka/blob/develop/setup.py#L28
# # https://github.com/spulec/moto/blob/master/setup.py#L39

WORKDIR $HOME
CMD ["/bin/bash"]
