apiVersion: v1
kind: Pod
metadata:
  name: test-root
spec:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
  containers:
    - name: test
      image: hysds-core:unity-v0.0.1
      command: ["supervisord", "--nodaemon"]
      volumeMounts:
        - name: celeryconfig
          mountPath: /home/ops/hysds/celeryconfig.py
          subPath: celeryconfig.py
        - name: supervisord-orchestrator
          mountPath: /etc/supervisord.conf
          subPath: supervisord.conf
        # - name: aws-credentials
        #   mountPath: /root/.aws/credentials
        #   subPath: aws-credentials
        - name: data-work
          mountPath: /private/tmp/data
  volumes:
    - name: celeryconfig
      configMap:
        name: celeryconfig
    - name: supervisord-orchestrator
      configMap:
        name: supervisord-orchestrator
    # - name: aws-credentials
    #   configMap:
    #     name: aws-credentials
    - name: data-work
      hostPath:
        path: /private/tmp/data
