apiVersion: v1
kind: Pod
metadata:
  name: celery-tasks
  labels:
    name: celery-tasks
spec:
  containers:
    - name: celery-tasks
      image: celery-tasks:unity-v0.0.1
      imagePullPolicy: IfNotPresent
