apiVersion: v1
kind: Pod
metadata:
  name: factotum-job-worker
spec:
  containers:
    - name: factotum-job-worker
      image: factotum:unity-v0.0.1
      command: ["supervisord", "--nodaemon"]
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
      volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
        - name: celeryconfig
          mountPath: /root/hysds/celeryconfig.py
          subPath: celeryconfig.py
        - name: datasets
          mountPath: /root/datasets.json
          subPath: datasets.json
        - name: supervisord-job-worker
          mountPath: /root/supervisord.conf
          subPath: supervisord.conf
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
    - name: celeryconfig
      configMap:
        name: celeryconfig
    - name: datasets
      configMap:
        name: datasets
    - name: supervisord-job-worker
      configMap:
        name: supervisord-job-worker
