apiVersion: v1
kind: Pod
metadata:
  name: factotum-job-worker
spec:
  containers:
    - name: factotum-job-worker
      image: factotum:unity-v0.0.1
      command: ["supervisord", "--nodaemon"]
      volumeMounts:
        # - name: docker-sock
        #   mountPath: /var/run/docker.sock
        - name: docker-sock
          mountPath: /var/run
        - name: celeryconfig
          mountPath: /home/ops/hysds/celeryconfig.py
          subPath: celeryconfig.py
        - name: datasets
          mountPath: /home/ops/datasets.json
          subPath: datasets.json
        - name: supervisord-job-worker
          mountPath: /home/ops/supervisord.conf
          subPath: supervisord.conf
  volumes:
    # - name: docker-sock
    #   hostPath:
    #     path: /var/run/docker.sock
    - name: docker-sock
      hostPath:
        path: /var/run
    - name: celeryconfig
      configMap:
        name: celeryconfig
    - name: datasets
      configMap:
        name: datasets
    - name: supervisord-job-worker
      configMap:
        name: supervisord-job-worker
