apiVersion: v1
kind: Pod
metadata:
  name: factotum-job-worker
spec:
  initContainers:
    - name: change-volume-ownership
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - chmod 777 /var/run/docker.sock;
          chown -R 1000:1000 /opt/data;
          # chmod -R 777 /tmp;
      volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
        # - name: work-pv-storage
        #   mountPath: /tmp
        - name: data-work
          mountPath: /opt/data

  containers:
    - name: factotum-job-worker
      image: factotum:unity-v0.0.1
      command: ["supervisord", "--nodaemon"]
      volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
        - name: celeryconfig
          mountPath: /home/ops/hysds/celeryconfig.py
          subPath: celeryconfig.py
        - name: datasets
          mountPath: /home/ops/datasets.json
          subPath: datasets.json
        - name: supervisord-job-worker
          mountPath: /home/ops/supervisord.conf
          subPath: supervisord.conf
        # - name: work-pv-storage
        #   mountPath: "/tmp"
        - name: data-work
          mountPath: /opt/data

  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
    - name: celeryconfig
      configMap:
        name: celeryconfig
    - name: datasets
      configMap:
        name: datasets
    - name: supervisord-job-worker
      configMap:
        name: supervisord-job-worker
    # - name: work-pv-storage
    #   persistentVolumeClaim:
    #     claimName: work-pv-claim
    - name: data-work
      hostPath:
        # path: /tmp
        path: /opt/data
