# Note: This Pod spec requires the Kubernetes feature gate "SidecarContainers"
# which is available as optional in Kubernetes 1.28 and enabled by default in Kubernetes 1.29
apiVersion: v1
kind: Pod
metadata:
  name: cwlpod
spec:
  containers:
    - name: cwl-docker
      image: lucacinquini/cwl-docker:latest
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run
        - name: tmp-dir
          mountPath: /tmp
      command: [ "sh", "-cx", "cwl-runner https://raw.githubusercontent.com/unity-sds/unity-sps-prototype/cwl-docker/cwl/cwl_workflows/hello_world_from_docker.cwl" ]
  initContainers:
    - name: dind
      image: docker:dind
      securityContext:
        privileged: true
      # "If an init container is created with its restartPolicy set to Always,
      # it will start and remain running during the entire life of the Pod."
      restartPolicy: Always
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run
        - name: tmp-dir
          mountPath: /tmp
  restartPolicy: Never
  volumes:
    - name: docker-socket
      emptyDir: { }
    - name: tmp-dir
      emptyDir: { }
