name: U-SPS Regression Test for MCP Dev

on:
  schedule:
    # Runs around midnight Pacific Time (UTC-7)
    # Doesn't account for daylight saving transitions
    - cron: "0 7 * * *"
  workflow_dispatch:
    inputs:
      AIRFLOW_ENDPOINT:
        description: "Base URL for the Airflow endpoint (i.e. http://abc.def.ghi:port-number)"
        type: string

jobs:
  print_inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Base URL for the Airflow endpoint (i.e. http://abc.def.ghi:port-number): ${{ github.event.inputs.AIRFLOW_ENDPOINT || vars.MCP_DEV_AIRFLOW_ENDPOINT }}"
  regression_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        working-directory: ${{ github.workspace }}/unity-test
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --use-pep517
      - name: Run the regression test
        working-directory: ${{ github.workspace }}/unity-test
        run: >
          pytest -s -vv --gherkin-terminal-reporter
          step_defs/test_airflow_api_health.py
          --airflow-endpoint=${{ github.event.inputs.AIRFLOW_ENDPOINT || vars.MCP_DEV_AIRFLOW_ENDPOINT }}
